baseURL = "https://jguhlke.de"
theme = "hugo-book"

author = "Jelmen Guhlke"
copyright = "© Jelmen Guhlke"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/JelmenGuhlke"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:mail@jguhlke.de"

[menu]


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

defaultContentLanguage = 'en-US'
defaultContentLanguageInSubdir = true
[languages]
  [languages.de]
    contentDir = 'content/de'
    disabled = false
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    title = 'Nachhaltige Entwicklung'
    weight = 1
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'sustainable development'
    weight = 2
  [languages.de_easy]
    contentDir = 'content/de_easy'
    disabled = false
    languageCode = 'de-DE-easy'
    languageDirection = 'ltr'
    languageName = 'Deutsch in einfacher Sprache'
    title = 'Nachhaltige Entwicklung'
    weight = 3
